/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_local_move/srv/Stop.srv */
#ifndef ROBOTINO_LOCAL_MOVE_SERVICE_STOP_H
#define ROBOTINO_LOCAL_MOVE_SERVICE_STOP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robotino_local_move
{
template <class ContainerAllocator>
struct StopRequest_ {
  typedef StopRequest_<ContainerAllocator> Type;

  StopRequest_()
  {
  }

  StopRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::robotino_local_move::StopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::StopRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopRequest
typedef  ::robotino_local_move::StopRequest_<std::allocator<void> > StopRequest;

typedef boost::shared_ptr< ::robotino_local_move::StopRequest> StopRequestPtr;
typedef boost::shared_ptr< ::robotino_local_move::StopRequest const> StopRequestConstPtr;


template <class ContainerAllocator>
struct StopResponse_ {
  typedef StopResponse_<ContainerAllocator> Type;

  StopResponse_()
  : result(false)
  {
  }

  StopResponse_(const ContainerAllocator& _alloc)
  : result(false)
  {
  }

  typedef uint8_t _result_type;
  uint8_t result;


  typedef boost::shared_ptr< ::robotino_local_move::StopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::StopResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopResponse
typedef  ::robotino_local_move::StopResponse_<std::allocator<void> > StopResponse;

typedef boost::shared_ptr< ::robotino_local_move::StopResponse> StopResponsePtr;
typedef boost::shared_ptr< ::robotino_local_move::StopResponse const> StopResponseConstPtr;

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Stop
} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::StopRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::StopRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::robotino_local_move::StopRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/StopRequest";
  }

  static const char* value(const  ::robotino_local_move::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::robotino_local_move::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_local_move::StopRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::StopResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::StopResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const  ::robotino_local_move::StopResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/StopResponse";
  }

  static const char* value(const  ::robotino_local_move::StopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool result\n\
\n\
\n\
";
  }

  static const char* value(const  ::robotino_local_move::StopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_local_move::StopResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::StopRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::StopResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robotino_local_move::Stop> {
  static const char* value() 
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const robotino_local_move::Stop&) { return value(); } 
};

template<>
struct DataType<robotino_local_move::Stop> {
  static const char* value() 
  {
    return "robotino_local_move/Stop";
  }

  static const char* value(const robotino_local_move::Stop&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robotino_local_move::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const robotino_local_move::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robotino_local_move::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/Stop";
  }

  static const char* value(const robotino_local_move::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robotino_local_move::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const robotino_local_move::StopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robotino_local_move::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/Stop";
  }

  static const char* value(const robotino_local_move::StopResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_SERVICE_STOP_H

