int8 color		
# Object color code
# 0 for ORANGE colored objects 
# 1 for YELLOW colored objects 
# 2 for BLUE colored objects 
# 3 for GREEN colored objects 
# 4 for RED colored objects 
# 5 for BLACK colored objects 
# 6 for PINK colored objects 
# 7 for PURPLE colored objects

bool verify_markers
# If this is true, this service will consider that the object has at least one marker

int8 specific_number_of_markers
# If verify_markers is true, the following condition will be processed: 
# If specify_number_of_markers > 0 this service will consider only the specific number of markers; else it will consider any number of markers on object

---

float32[] distances	
# Object distance

float32[] directions	
# Object direction

int8[] number_of_markers
# Number of markers on object
