string imgPath  # an input parameter that informes the image path in which this will be processed
uint8 color	# an input parameter that informes the puck color
			# 0 represents red color
			# 1 represents orange color
			# 2 represents yellow color
			# 3 represents green color
			# 4 represents blue color 
			# 5 represents black color 
---

