# Goal Definition

uint8 module		# 0 for Module A and 1 for Module B.
---
# Result Definition

bool achieved_goal 	#if true, the goal has been achieved. Otherwise, it's false.
---
# Feedback Definition

float32 percentage	# from 0% through 100% for the completeness of the process.
