(cl:defpackage robotino_local_move-msg
  (:use )
  (:export
   "<LOCALMOVEACTIONFEEDBACK>"
   "LOCALMOVEACTIONFEEDBACK"
   "<LOCALMOVEACTIONRESULT>"
   "LOCALMOVEACTIONRESULT"
   "<LOCALMOVEACTION>"
   "LOCALMOVEACTION"
   "<LOCALMOVEGOAL>"
   "LOCALMOVEGOAL"
   "<PATHDISPLACEMENTS>"
   "PATHDISPLACEMENTS"
   "<LOCALMOVERESULT>"
   "LOCALMOVERESULT"
   "<LOCALMOVEFEEDBACK>"
   "LOCALMOVEFEEDBACK"
   "<LOCALMOVEACTIONGOAL>"
   "LOCALMOVEACTIONGOAL"
   "<PATHSTATUS>"
   "PATHSTATUS"
  ))

