; Auto-generated. Do not edit!


(cl:in-package robotino_local_move-msg)


;//! \htmlinclude LocalMoveResult.msg.html

(cl:defclass <LocalMoveResult> (roslisp-msg-protocol:ros-message)
  ((goal_reached
    :reader goal_reached
    :initarg :goal_reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LocalMoveResult (<LocalMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robotino_local_move-msg:<LocalMoveResult> is deprecated: use robotino_local_move-msg:LocalMoveResult instead.")))

(cl:ensure-generic-function 'goal_reached-val :lambda-list '(m))
(cl:defmethod goal_reached-val ((m <LocalMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotino_local_move-msg:goal_reached-val is deprecated.  Use robotino_local_move-msg:goal_reached instead.")
  (goal_reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalMoveResult>) ostream)
  "Serializes a message object of type '<LocalMoveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'goal_reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalMoveResult>) istream)
  "Deserializes a message object of type '<LocalMoveResult>"
    (cl:setf (cl:slot-value msg 'goal_reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalMoveResult>)))
  "Returns string type for a message object of type '<LocalMoveResult>"
  "robotino_local_move/LocalMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalMoveResult)))
  "Returns string type for a message object of type 'LocalMoveResult"
  "robotino_local_move/LocalMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalMoveResult>)))
  "Returns md5sum for a message object of type '<LocalMoveResult>"
  "a65bc774d2139031955fd7cc94fdd40f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalMoveResult)))
  "Returns md5sum for a message object of type 'LocalMoveResult"
  "a65bc774d2139031955fd7cc94fdd40f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalMoveResult>)))
  "Returns full string definition for message of type '<LocalMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool goal_reached #true if goal is reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalMoveResult)))
  "Returns full string definition for message of type 'LocalMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool goal_reached #true if goal is reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalMoveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalMoveResult
    (cl:cons ':goal_reached (goal_reached msg))
))
