/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_local_move/msg/LocalMoveResult.msg */
#ifndef ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVERESULT_H
#define ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVERESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robotino_local_move
{
template <class ContainerAllocator>
struct LocalMoveResult_ {
  typedef LocalMoveResult_<ContainerAllocator> Type;

  LocalMoveResult_()
  : goal_reached(false)
  {
  }

  LocalMoveResult_(const ContainerAllocator& _alloc)
  : goal_reached(false)
  {
  }

  typedef uint8_t _goal_reached_type;
  uint8_t goal_reached;


  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LocalMoveResult
typedef  ::robotino_local_move::LocalMoveResult_<std::allocator<void> > LocalMoveResult;

typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult> LocalMoveResultPtr;
typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult const> LocalMoveResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_local_move::LocalMoveResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::LocalMoveResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a65bc774d2139031955fd7cc94fdd40f";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa65bc774d2139031ULL;
  static const uint64_t static_value2 = 0x955fd7cc94fdd40fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/LocalMoveResult";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool goal_reached #true if goal is reached\n\
\n\
";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.goal_reached);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalMoveResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_local_move::LocalMoveResult_<ContainerAllocator> & v) 
  {
    s << indent << "goal_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_reached);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVERESULT_H

