/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_local_move/msg/LocalMoveActionGoal.msg */
#ifndef ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVEACTIONGOAL_H
#define ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVEACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "robotino_local_move/LocalMoveGoal.h"

namespace robotino_local_move
{
template <class ContainerAllocator>
struct LocalMoveActionGoal_ {
  typedef LocalMoveActionGoal_<ContainerAllocator> Type;

  LocalMoveActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  LocalMoveActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::robotino_local_move::LocalMoveGoal_<ContainerAllocator>  _goal_type;
   ::robotino_local_move::LocalMoveGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LocalMoveActionGoal
typedef  ::robotino_local_move::LocalMoveActionGoal_<std::allocator<void> > LocalMoveActionGoal;

typedef boost::shared_ptr< ::robotino_local_move::LocalMoveActionGoal> LocalMoveActionGoalPtr;
typedef boost::shared_ptr< ::robotino_local_move::LocalMoveActionGoal const> LocalMoveActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "68a36fa3b32a4bc7c7deca214daf5836";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x68a36fa3b32a4bc7ULL;
  static const uint64_t static_value2 = 0xc7deca214daf5836ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/LocalMoveActionGoal";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
LocalMoveGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32 move_x		# in meters\n\
float32 move_y		# in meters\n\
float32 rotation	# in rad\n\
uint8 movementType	\n\
# 0 -> Translational Movement (move_phi should be equal to zero)\n\
# 1 -> Rotational Movement (move_x and move_y should be equal to zero)\n\
# 2 -> Translational and Rotational Moviment (at the same time)\n\
# 3 -> Tangent Moviment (move_x must be iqual to move_y)\n\
\n\
#bool ignore_rotation #if true robot is not rotated after moving. if false robot is rotated \"rotation\" relative to the starting orientation\n\
\n\
";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalMoveActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::robotino_local_move::LocalMoveGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVEACTIONGOAL_H

