/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_local_move/msg/LocalMoveAction.msg */
#ifndef ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVEACTION_H
#define ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVEACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "robotino_local_move/LocalMoveActionGoal.h"
#include "robotino_local_move/LocalMoveActionResult.h"
#include "robotino_local_move/LocalMoveActionFeedback.h"

namespace robotino_local_move
{
template <class ContainerAllocator>
struct LocalMoveAction_ {
  typedef LocalMoveAction_<ContainerAllocator> Type;

  LocalMoveAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  LocalMoveAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator>  _action_goal_type;
   ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::robotino_local_move::LocalMoveActionResult_<ContainerAllocator>  _action_result_type;
   ::robotino_local_move::LocalMoveActionResult_<ContainerAllocator>  action_result;

  typedef  ::robotino_local_move::LocalMoveActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::robotino_local_move::LocalMoveActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LocalMoveAction
typedef  ::robotino_local_move::LocalMoveAction_<std::allocator<void> > LocalMoveAction;

typedef boost::shared_ptr< ::robotino_local_move::LocalMoveAction> LocalMoveActionPtr;
typedef boost::shared_ptr< ::robotino_local_move::LocalMoveAction const> LocalMoveActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_local_move::LocalMoveAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::LocalMoveAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41b1ca15437c0f8a731cc1f81618c3b";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41b1ca15437c0f8ULL;
  static const uint64_t static_value2 = 0xa731cc1f81618c3bULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/LocalMoveAction";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
LocalMoveActionGoal action_goal\n\
LocalMoveActionResult action_result\n\
LocalMoveActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
LocalMoveGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32 move_x		# in meters\n\
float32 move_y		# in meters\n\
float32 rotation	# in rad\n\
uint8 movementType	\n\
# 0 -> Translational Movement (move_phi should be equal to zero)\n\
# 1 -> Rotational Movement (move_x and move_y should be equal to zero)\n\
# 2 -> Translational and Rotational Moviment (at the same time)\n\
# 3 -> Tangent Moviment (move_x must be iqual to move_y)\n\
\n\
#bool ignore_rotation #if true robot is not rotated after moving. if false robot is rotated \"rotation\" relative to the starting orientation\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
LocalMoveResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool goal_reached #true if goal is reached\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
LocalMoveFeedback feedback\n\
\n\
================================================================================\n\
MSG: robotino_local_move/LocalMoveFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float32 forward_dist_x	# forward distance to goal in x\n\
float32 forward_dist_y	# forward distance to goal in y\n\
float32 rotation_dist	# rotationaldistance to goal\n\
\n\
\n\
";
  }

  static const char* value(const  ::robotino_local_move::LocalMoveAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalMoveAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_local_move::LocalMoveAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_local_move::LocalMoveAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::robotino_local_move::LocalMoveActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::robotino_local_move::LocalMoveActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::robotino_local_move::LocalMoveActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVEACTION_H

