/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_local_move/msg/PathDisplacements.msg */
#ifndef ROBOTINO_LOCAL_MOVE_MESSAGE_PATHDISPLACEMENTS_H
#define ROBOTINO_LOCAL_MOVE_MESSAGE_PATHDISPLACEMENTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robotino_local_move
{
template <class ContainerAllocator>
struct PathDisplacements_ {
  typedef PathDisplacements_<ContainerAllocator> Type;

  PathDisplacements_()
  : move_x(0.0)
  , move_y(0.0)
  , rotation(0.0)
  , movementType(0)
  {
  }

  PathDisplacements_(const ContainerAllocator& _alloc)
  : move_x(0.0)
  , move_y(0.0)
  , rotation(0.0)
  , movementType(0)
  {
  }

  typedef float _move_x_type;
  float move_x;

  typedef float _move_y_type;
  float move_y;

  typedef float _rotation_type;
  float rotation;

  typedef uint8_t _movementType_type;
  uint8_t movementType;


  typedef boost::shared_ptr< ::robotino_local_move::PathDisplacements_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::PathDisplacements_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PathDisplacements
typedef  ::robotino_local_move::PathDisplacements_<std::allocator<void> > PathDisplacements;

typedef boost::shared_ptr< ::robotino_local_move::PathDisplacements> PathDisplacementsPtr;
typedef boost::shared_ptr< ::robotino_local_move::PathDisplacements const> PathDisplacementsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_local_move::PathDisplacements_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_local_move::PathDisplacements_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::PathDisplacements_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::PathDisplacements_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::PathDisplacements_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9b998c7d1cd4ec3c3324c335d8cef150";
  }

  static const char* value(const  ::robotino_local_move::PathDisplacements_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9b998c7d1cd4ec3cULL;
  static const uint64_t static_value2 = 0x3324c335d8cef150ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::PathDisplacements_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/PathDisplacements";
  }

  static const char* value(const  ::robotino_local_move::PathDisplacements_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::PathDisplacements_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 move_x		# in meters\n\
float32 move_y		# in meters\n\
float32 rotation	# in degrees\n\
\n\
uint8 movementType	\n\
# 0 -> Translational Movement (move_phi should be equal to zero)\n\
# 1 -> Rotational Movement (move_x and move_y should be equal to zero)\n\
# 2 -> Translational and Rotational Moviment (at the same time)\n\
# 3 -> Tangent Moviment (move_x must be iqual to move_y)\n\
\n\
";
  }

  static const char* value(const  ::robotino_local_move::PathDisplacements_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_local_move::PathDisplacements_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::PathDisplacements_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.move_x);
    stream.next(m.move_y);
    stream.next(m.rotation);
    stream.next(m.movementType);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PathDisplacements_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_local_move::PathDisplacements_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_local_move::PathDisplacements_<ContainerAllocator> & v) 
  {
    s << indent << "move_x: ";
    Printer<float>::stream(s, indent + "  ", v.move_x);
    s << indent << "move_y: ";
    Printer<float>::stream(s, indent + "  ", v.move_y);
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
    s << indent << "movementType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.movementType);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_MESSAGE_PATHDISPLACEMENTS_H

